### ISSUE TITLE
early todo

### ISSUE THREAD

**Issue by mdsumner** [hypertidy/textures#2]
- [x] write cpp versions of `ib_index` and `vb_vertex`
- [x] allow ydown in R code ( needs reversing index direction)
- [x] allow ydown in C++ code
- [ ] ~allow more general orientation? (index vs. native coordinates is independent ... so it's all up for grabs)~ let's not go there
- [x] write triangle versions of quad() in R
- [ ] ~write triangle versions of quad() in C++~ needs though, another todo list
- [ ] ~write cpp versions of divide.mesh3d~ see #5

**Comment by mdsumner** [comment]
Current design is 

### Headers 

`./inst/include/quad/quad.h` namespace `quad`

```C++
// returns nx * ny mesh3d$ib (a 4 * (nx * ny) matrix with a column for each quad
IntegerVector quad_ib(IntegerVector nx, IntegerVector ny, LogicalVector ydown);
// returns nx * ny mesh3d$vb[1:2, ] (a 2 * ((nx+1) * (ny+1)) matrix of xy)
NumericVector quad_vb(IntegerVector nx, IntegerVector ny, LogicalVector ydown);
```

Quad indexes are counter-clockwise, as required by rgl (see `material3d` `back` argument).

### Rcpp package using quad.h

Wrap `quad_ib` and `quad_vb` callable from R. 

```C++
IntegerVector quad_index_cpp(IntegerVector nx, IntegerVector ny, LogicalVector ydown) 
NumericVector quad_vertex_cpp(IntegerVector nx, IntegerVector ny, LogicalVector ydown) 
```

All coordinates are in  `x [0, 1]` and `y [0, 1]` and default to "y-up" (begin at 0)

`ydown` ensures that y coordinates begin at 1 and count down, and that quad indexes are reversed and correctly counter-clockwise.

**Comment by mdsumner** [comment]
Need to 

- [ ] ensure unmesh is unused
- [ ] test for change in index order in break_mesh() (or break in a way that doesn't do that)
- [ ] check that break_mesh doesn't mess up orientation
- [ ] test for ydown difference

**Comment by mdsumner** [comment]
Design above now in master with https://github.com/hypertidy/textures/pull/4
